# Generated by Django 3.1.7 on 2021-03-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='1', max_length=254),
            preserve_default=False,
        ),
    ]
