# Generated by Django 3.1.7 on 2021-03-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
