# Generated by Django 3.1.7 on 2021-03-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazzar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
    ]
