# Generated by Django 3.1.7 on 2021-03-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazzar', '0005_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.IntegerField(),
        ),
    ]
