# Generated by Django 3.1.7 on 2021-03-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazzar', '0009_auto_20210309_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.IntegerField(default='8317404976'),
        ),
    ]
